#!/bin/bash
google-chrome http://pm.redox.ca/dashboard http://habrahabr.ru/hub/webdev/ http://habrahabr.ru/hub/programming/ http://habrahabr.ru/posts/top/ http://habrahabr.ru/hub/yii/ http://habrahabr.ru/hub/php/ http://habrahabr.ru/hub/javascript/ https://www.google.md/
